stages:
  - build
  - test

# Define a job for the build stage
build:
  stage: build
  image: gcc:latest
  script:
    - echo "Building the project..."

# Define a job for the test stage
test:
  stage: test
  image: gcc:latest
  dependencies:
    - build
  script:
    - echo "Running tests..."