stages:
  - compile
  - check
  - test


compile:
  stage: compile
  image: pp-oneapi-bundle
  needs: [ ]
  tags:
    - pp-runner
  script:
    - ./config.sh --tests
    - ./clean_build.sh



check:
  stage: check
  image: pp-oneapi-bundle
  needs: [ ]
  allow_failure: true
  tags:
    - pp-runner
  script:
    - ./config.sh --examples
    - ./clean_build.sh
    - cppcheck --project=bin/compile_commands.json

test:
  stage: test
  image: pp-oneapi-bundle
  needs: [ ]
  tags:
    - pp-runner
  script:
    - ./config.sh --tests
    - ./clean_build.sh
    - cd ./bin && ctest -v
